KORIT-LSLC/KORIT-LSLC-portfolio-front

- trip_location/package-lock.json
- trip_location/package.json
> feet#1: 리액트 라이브러리 추가(리액트 아이콘/ 리액트라우터돔/ 이모션)

- trip_location/package-lock.json
- trip_location/package.json
- trip_location/src/components/contents/main/PopularDestinations.js
- trip_location/src/pages/Home.js
본래 슬라이더는 버튼이라던지 애매하게 들어가지 않던부분을 라이브러리를 쓰면서 완벽하게 바꿨음
> feat: mui-carousel 라이브러리이용 슬라이더 구현

- trip_location/src/App.js
- trip_location/src/components/contents/Map/Map.js
- trip_location/src/components/contents/Modal/Modal.js
- trip_location/src/pages/Contents/Contents.js
- trip_location/src/pages/Home.js
> feat: modal 에서 content로 넘어가는 props 조정

- trip_location/src/components/Button/SubButton.js
- trip_location/src/components/Button/ToggleButton.js
- trip_location/src/components/Calendar/Calendar.js
- trip_location/src/components/Tab/Tab.js
- trip_location/src/pages/Contents/Contents.js
Feat: SubButton과 Tab을 넣어서 왼쪽사이바를 추가 및 수정
> Feat: SubButton과 Tab을 넣어서 왼쪽사이바를 추가 및 수정

- trip_location/package-lock.json
- trip_location/package.json
- trip_location/src/App.js
- trip_location/src/api/Auth/AuthApi.js
- trip_location/src/atoms/Auth/AuthAtoms.js
- trip_location/src/components/Nav/Nav.js
- trip_location/src/components/Routes/AuthRoute/AuthRouter.js
- trip_location/src/components/contents/ModifyForm/ModifyForm.js
- trip_location/src/index.js
- trip_location/src/pages/Login/Login.js
- trip_location/src/pages/MyPage.js
로그인이 되었을 경우 보여지는 페이지 그리고 로그인이 되지않았을 때 보여지는 페이지의 구분이 완성되고 mypage에서 수정하기 버튼눌렀을 때 폼이 나오는 것을 구현
> feat: mypage 와 login 됬을 때 페이지들 변경사항

- trip_location/src/components/contents/ModifyForm/ModifyForm.js
- trip_location/src/pages/MyPage.js
버튼들이 모두 같은 행동을 하던 것을 하나하나 다른 행동을 하도록 바꾸고 마지막에 버튼을 누를경우 수정할 수 있게 put 요청까지는 보냈으나 403에러 마주침
> fixed: mypage 버튼활동 수정 및 업데이트

- trip_location/src/components/Calendar/Calendar.js
- trip_location/src/components/Tab/Tab.js
- trip_location/src/components/contents/Map/Map.js
- trip_location/src/pages/Contents/Contents.js
문제는 전체의 일정이 올라가지 않는다는 점이 있어 수정해야함.
> Feat: 콘텐프 페이지에서 최종 여행의 일정이 올라감.

- trip_location/src/App.js
- trip_location/src/atoms/Auth/AuthAtoms.js
- trip_location/src/components/Nav/Nav.js
- trip_location/src/components/Routes/AuthRoute/AuthRouter.js
- trip_location/src/components/contents/ModifyForm/ModifyForm.js
- trip_location/src/pages/Home.js
- trip_location/src/pages/Login/Login.js
> fixed: auth router 부분 수정중에 있음

- trip_location/src/pages/Login/Login.js
- trip_location/src/pages/PasswordReset/CheckEmail.js
- trip_location/src/pages/PasswordReset/PasswordReset.js
> 비밀번호 초기화 디자인 수정 중

- trip_location/src/components/contents/ModifyForm/ModifyForm.js
user 정보 수정 페이지
- 유저 정보 새로고침 시 user 정보 유지
- 주소 리스트 값 선택 수정
> mypage user 정보 수정 페이지 로직 수정

- trip_location/src/components/Calendar/Calendar.js
- trip_location/src/components/Tab/Tab.js
- trip_location/src/pages/Contents/Contents.js
> Fix: Tab컴퍼넌트에서 객체배열로 변경

- trip_location/src/components/contents/ModifyForm/ModifyForm.js
mypage
- profileImg css
- name/phone validation onChangeHandler
> mypage profileImg 위치, name/phone validaion check

- trip_location/src/components/Calendar/Calendar.js
- trip_location/src/components/Tab/Tab.js
- trip_location/src/components/contents/Map/Map.js
- trip_location/src/pages/Contents/Contents.js
[
{
id:1,
date:'일자',
location:
[
{
addr:
lat:
lng:
}
]
}
]
> Fix: dataStructor의 구성을 수정하였음.

- trip_location/src/components/Nav/Nav.js
- trip_location/src/components/Routes/AuthRoute/AuthRouter.js
- trip_location/src/pages/Login/Login.js
- trip_location/src/pages/SignUp/OAuth2/OAuth2Register.js
> fixed: oauth에대한 수정과 로그인 엔터기능

- trip_location/src/components/Calendar/Calendar.js
- trip_location/src/components/Tab/Tab.js
- trip_location/src/components/contents/Map/Map.js
- trip_location/src/pages/Contents/Contents.js
다음 문제 예상으로 경로에 대한 수정 부분을 어떻게 할것인지 문제이다.
> Fix: Tab 컴포넌트에서 scheduleData 구성에 맞게 수정

- trip_location/src/components/Calendar/Calendar.js
- trip_location/src/components/contents/Modal/AddUserModal.js
- trip_location/src/pages/Contents/Contents.js
> Feat: AddUserModal을 만들어서 함께갈 친구 추가.

- trip_location/src/App.js
- trip_location/src/pages/Login/OAuth2Login/OAuth2Login.js
- trip_location/src/pages/SignUp/OAuth2/OAuth2Merge.js
> feat: Oauth2 로그인 회원가입 완료

- trip_location/src/App.js
- trip_location/src/components/contents/ModifyForm/ModifyForm.js
- trip_location/src/pages/Login/Login.js
- trip_location/src/pages/PasswordReset/CheckEmail.js
- trip_location/src/pages/PasswordReset/PasswordReset.js
비밀번호 초기화 디자인과 기능 수정 완료
- user 이메일 확인 후 resetPassword 받아서 user 정보 수정
- 새로운 비밀번호로 로그인 확인 완료
> forgorPassord 시 비밀번호 초기화 디자인과 기능 완료

- trip_location/src/components/contents/Modal/Modal.js
메인화면 > locationcard modal 선택 시 각 지역의 설명 추가
> LocationCard Modal 선택시 각 지역마다 설명 추가

- trip_location/src/components/Calendar/Calendar.js
> fixed: 여행 경로 들고가는 것

- trip_location/src/components/contents/main/LocationCard.js
- trip_location/src/pages/Home.js
- 메인페이지에서 지역 검색 가능 (한글, 영어 - 대소문자 구분 X)
- footer css 수정
> 메인페이지 LocationCard 한글, 영어 검색 기능 완료, footer css 수정

- trip_location/src/components/contents/ModifyForm/ModifyForm.js
아직 사진이 변경되지는 않습니다. 처음 회원가입시에 디폴트 이미지를 넣어주어야 할 것같습니다
> feat: 회원 정보 수정시 이미지 변경 업로드만 구현

- trip_location/src/App.js
- trip_location/src/pages/CheckItinerary/CheckMyTrip.js
> feat: 나의 여행일정 확인페이지

- trip_location/src/components/contents/ModifyForm/ModifyForm.js
- trip_location/src/pages/MyPage.js
> feat: 마이페이지 및 회원정보 프로필사진

- trip_location/src/App.js
- trip_location/src/components/contents/ModifyForm/RegionRegister.js
> modal admin page 생성

- trip_location/src/components/contents/Modal/AddUserModal.js
- trip_location/src/pages/Contents/Contents.js
partyData에 옮겨 나중 schedulData에 함께올리도록 함.
> Fix: 검색한 유저를 partyUser에 넣고

- trip_location/src/App.js
- trip_location/src/components/Calendar/Calendar.js
- trip_location/src/components/contents/ModifyForm/ModifyForm.js
- trip_location/src/pages/CheckItinerary/CheckMyTrip.js
- trip_location/src/pages/MyPage.js
- trip_location/src/pages/TravelList/TravelList.js
> feat: 여행 저장후 나의 일정보기 작업

- trip_location/src/pages/CheckItinerary/CheckMyTrip.js
마커들 따로 움직이고 각각의 마커에 대한 정보들을 받아서 저장완료
> feat: 여행 경로 정보 변경 수정 완료

- trip_location/src/App.js
- trip_location/src/pages/review/Review.js
> feat: 리뷰 볼 수 있는 페이지 생성

- trip_location/src/App.js
- trip_location/src/components/Calendar/Calendar.js
- trip_location/src/components/Nav/Nav.js
- trip_location/src/components/Routes/AuthRoute/AuthRouter.js
- trip_location/src/components/TravelList/TravelList.js
- trip_location/src/components/contents/Modal/AddUserModal.js
- trip_location/src/components/contents/Modal/Modal.js
- trip_location/src/components/contents/ModifyForm/ModifyForm.js
- trip_location/src/pages/CheckItinerary/CheckMyTrip.js
- trip_location/src/pages/Contents/Contents.js
- trip_location/src/pages/Home.js
- trip_location/src/pages/Login/Login.js
- trip_location/src/pages/Login/OAuth2Login/OAuth2Login.js
- trip_location/src/pages/MyPage.js
- trip_location/src/pages/NewPassword/ModifyPassword.js
- trip_location/src/pages/TravelList/TravelList.js
- trip_location/src/store/atoms/AuthAtoms.js
해당 principal 들 모두 enabled에 authState.isAuthenticated를 추가해줌
> fixed: princpal 인증 부분관련

- trip_location/src/App.js
- trip_location/src/components/TravelList/TravelList.js
- trip_location/src/pages/CheckItinerary/CheckMyTrip.js
- trip_location/src/pages/Contents/Contents.js
- trip_location/src/pages/MyPage.js
> Fix: MyTravel별로 사진, 일정, 위치 카드에 들고오도록 수정.

- trip_location/src/App.js
- trip_location/src/components/contents/ModifyForm/ModifyForm.js
- trip_location/src/pages/NewPassword/PasswordReset.js
- trip_location/src/pages/SignUp/SignUp.js
- trip_location/src/pages/Withdrawal/Withdrawal.js
- 회원 정보 수정페이지에서 회원 탈퇴 Link 연결 완료
- 회원 탈퇴 페이지 디자인 완료
- 탈퇴 기능 구현 중
> 회원 탈퇴 페이지 디자인 완료, 기능 구현중

- trip_location/src/components/Button/NavBarButton.js
- trip_location/src/components/contents/ModifyForm/ModifyForm.js
- trip_location/src/pages/Withdrawal/Withdrawal.js
유저 탈퇴 페이지에서 dialog transition으로 클릭 이벤트 막히던 오류 수정
> 유저 탈퇴 페이지 dialog 클릭이벤트 오류 수정

- trip_location/src/pages/CheckItinerary/CheckMyTrip.js
- trip_location/src/pages/Contents/Contents.js
- trip_location/src/pages/MyPage.js
- trip_location/src/pages/review/ModifyReviewForm.js
CheckMyTrip에서  update성공하면 `/user/${searchParams.get('userId')}로 수정
> fix: Contents페이지에서 accessToken local에서 받는 부분 제거 수정.

- trip_location/src/pages/CheckItinerary/CheckMyTrip.js
- trip_location/src/pages/CheckItinerary/styles/CheckPageStyles.js
나의 일정 확인 페이지 디자인 수정 중
- Day 버튼
- 일정 리스트
> 나의 일정 확인 페이지 날짜 버튼, 일정 리스트 디자인 수정 중

- trip_location/src/pages/CheckItinerary/CheckMyTrip.js
- trip_location/src/pages/CheckItinerary/styles/CheckPageStyles.js
mypage > 일정 확인 page
- 기존에 있던 요소들 디자인 수정 완료
> 일정 확인 페이지 기존 요소 디자인 완료

- trip_location/src/pages/CheckItinerary/CheckMyTrip.js
- trip_location/src/pages/CheckItinerary/WriteReview.js
- trip_location/src/pages/CheckItinerary/styles/CheckPageStyles.js
리뷰 작성 페이지 디자인 수정 중
- day 버튼
- map, locList
> 리뷰 작성페이지 디자인 수정 중

- trip_location/src/App.css
- trip_location/src/pages/CheckItinerary/CheckMyTrip.js
- trip_location/src/pages/CheckItinerary/WriteReview.js
- trip_location/src/pages/CheckItinerary/styles/CheckPageStyles.js
리뷰 작성 페이지 디자인
- contents 영역 디자인 전부 수정
> 리뷰 작성 페이지 디자인 완료

- trip_location/src/pages/CheckItinerary/WriteReview.js
- trip_location/src/pages/CheckItinerary/styles/CheckPageStyles.js
- trip_location/src/pages/review/ReviewDetail.js
- trip_location/src/pages/review/styles/ReivewStyles.js
리뷰 디테일 페이지 디자인 수정 완료
- map
- locationList
- title
- getRoute
- img
- contents
> fix: 리뷰 디테일 페이지 디자인 수정 완료

- trip_location/src/components/Calendar/Calendar.js
- trip_location/src/components/TravelList/TravelList.js
- trip_location/src/pages/MyPage.js
> Feat/Fix: 리뷰작성이된 일정은 리뷰작성완료가 나오도록 추가 수정함.

- trip_location/src/components/Calendar/Calendar.js
- trip_location/src/components/Calendar/styles/CalendarStyles.js
- trip_location/src/components/Tab/Tab.js
- trip_location/src/components/contents/Map/Map.js
- trip_location/src/components/contents/Map/styles/MapStyles.js
- trip_location/src/pages/CheckItinerary/CheckCopyTrip.js
- trip_location/src/pages/CheckItinerary/styles/CheckPageStyles.js
- trip_location/src/pages/Contents/Contents.js
- trip_location/src/pages/Contents/styles/ContentStyles.js
> 전체적인 css 수정완료
